import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import Contact from '../components/Contact/Contact'
import MainComp from '../components/Main/MainComp'
import Servc from '../components/Servc/Servc'
import Slider from '../components/Slider/Slider'
import styles from '../styles/Home.module.css'
import Whyus from './../components/Whyus/Whyus';

const Home: NextPage = () => {
  return (
    <MainComp>
      <div className={styles.container}>
        <Head>
          <title>Auto salon</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
      <Servc/>
      <Whyus/>
      {/* <Slider/> */}
      <Contact/>
    </MainComp>
  )
}

export default Home
